force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Meetup information.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>Random and unique identifier for a meetup.</description>
    <externalId>true</externalId>
    <inlineHelpText>Random and unique identifier for a meetup.</inlineHelpText>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MeetupTriggerHandler.cls
/**
 * Generally try to avoid generic, all encompassing trigger handlers
 * even if those handlers call service methods from other classes
 * Rather I prefer to inject the business logic to be executed at runtime
 * using a bit of DI/IoC with custom metadata pointing to handlers that execute
 * a single bit of business logic. That generally makes things more testable, manageable,
 * and gives us a nice way to easily feature flag automation settings
 * 
 * For the purposes of this interview question, just having a simple handler to show
 * decomp and the importance of moving logic out of the trigger itself
 */
public inherited sharing class MeetupTriggerHandler {
    public void doBeforeInsert(List<Meetup__c> triggerNewList) {
        for (Meetup__c meetup : triggerNewList) {
            if (String.isBlank(meetup.RegistrationCode__c)) {
                meetup.RegistrationCode__c = Services.strings.getRandomAlphaNumericString(8);
            }
        }
    }
}