force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Meetup information.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>Random and unique identifier for a meetup.</description>
    <externalId>true</externalId>
    <inlineHelpText>Random and unique identifier for a meetup.</inlineHelpText>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The maximum number of registrations for a meetup.</description>
    <inlineHelpText>The maximum number of registrations for a meetup.</inlineHelpText>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Registrations__c.field-meta.xml
<CustomField>
    <fullName>Registrations__c</fullName>
    <description>The current number of registrations for the meetup.</description>
    <inlineHelpText>The current number of registrations for the meetup.</inlineHelpText>
    <label>Registrations</label>
    <summaryForeignKey>MeetupRegistration__c.Meetup__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Meetup Registration Status.</description>
    <inlineHelpText>Meetup Registration Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <description>Individual user registration for a meetup.</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>MR-{0}</displayFormat>
        <label>Meetup Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Registrant email.</description>
    <inlineHelpText>Registrant email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>The meetup that a registration is for.</description>
    <inlineHelpText>The meetup that a registration is for.</inlineHelpText>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>Meetup_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MeetupSelector.cls
/**
 * Would generally have this implement a base abstract class as part of a broader
 * secure by default data library, but just separating for this to show proper separation of 
 * concerns
 */
public inherited sharing class MeetupSelector {
    public List<Meetup__c> getMeetupsByRegistrationCode(Set<String> registrationCodes, Boolean enforceFLS) {
        // would normally have this be some sort of query builder as a part of the 
        // data library, but just do inline soql for now
        // note the data library would also be used to enforce/not enforce security, so we wouldn't
        // have to hard code it in queries and do this weird dance with enforce FLS checks
        return (List<Meetup__c>) Database.query(this.getQuery('RegistrationCode__c IN :registrationCodes', enforceFLS));
    }

    public List<Meetup__c> getMeetupsById(Set<Id> meetupIds, Boolean enforceFLS) {
        // would normally have this be some sort of query builder as a part of the 
        // data library, but just do inline soql for now
        // note the data library would also be used to enforce/not enforce security, so we wouldn't
        // have to hard code it in queries and do this weird dance with enforce FLS checks
        return (List<Meetup__c>) Database.query(this.getQuery('Id IN :meetupIds', enforceFLS));
    }

    // wouldnt usually use something like this -- that is usually managed by the data framework
    // to make queries more composable
    private String getQuery(String filter, Boolean enforceFLS) {
        String query = 'SELECT Id, Status__c, RegistrationLimit__c, Registrations__c, ' 
        + ' (SELECT Email__c FROM Meetup_Registrations__r)' 
        + ' FROM Meetup__c WHERE ' + filter;
        if (enforceFLS) {
            query += ' WITH SECURITY_ENFORCED';
        }
        return query;
    }
}