force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Meetup information.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>Random and unique identifier for a meetup.</description>
    <externalId>true</externalId>
    <inlineHelpText>Random and unique identifier for a meetup.</inlineHelpText>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The maximum number of registrations for a meetup.</description>
    <inlineHelpText>The maximum number of registrations for a meetup.</inlineHelpText>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Meetup Registration Status.</description>
    <inlineHelpText>Meetup Registration Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <description>Individual user registration for a meetup.</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>MR-{0}</displayFormat>
        <label>Meetup Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Registrant email.</description>
    <inlineHelpText>Registrant email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Registrant First Name.</description>
    <inlineHelpText>Registrant First Name.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Registrant Last Name.</description>
    <inlineHelpText>Registrant Last Name.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>The meetup that a registration is for.</description>
    <inlineHelpText>The meetup that a registration is for.</inlineHelpText>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>Meetup_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tests/MeetupRegistrationControllerTest.cls
@IsTest
private inherited sharing class MeetupRegistrationControllerTest {
    // Would generally mock out dependencies here with a generic class mocker
    @IsTest
    private static void getAvailableMeetupIdForCode_noCode_throwException() {
        String err;
        System.Test.startTest();
        try {
            MeetupRegistrationController.getAvailableMeetupIdForCode(null);
        } catch (AuraHandledException e) {
            err = e.getMessage();
        }
        System.Test.stopTest();
        Assert.isTrue(err.contains(MeetupRegistrationController.REGISTRATION_CODE_REQUIRED), 'Should throw the no code exception');
    }

    @IsTest
    private static void getAvailableMeetupIdForCode_noMeetups_throwException() {
        String err;
        System.Test.startTest();
        try {
            MeetupRegistrationController.getAvailableMeetupIdForCode('abcd1234');
        } catch (AuraHandledException e) {
            err = e.getMessage();
        }
        System.Test.stopTest();
        Assert.isTrue(err.contains(MeetupRegistrationController.MEETUP_NOT_FOUND), 'Should throw the no meetup exception');
    }

    @IsTest
    private static void getAvailableMeetupIdForCode_meetupClosed_throwException() {
        insert new Meetup__c(RegistrationLimit__c = 1, Status__c = 'Closed');
        // a reason to mock -- even our test setup is an integration test that requires 
        // automation to work
        Meetup__c meetup = [SELECT RegistrationCode__c FROM Meetup__c LIMIT 1];
        String err;
        System.Test.startTest();
        try {
            MeetupRegistrationController.getAvailableMeetupIdForCode(meetup.RegistrationCode__c);
        } catch (AuraHandledException e) {
            err = e.getMessage();
        }
        System.Test.stopTest();
        Assert.isTrue(err.contains(MeetupRegistrationController.MEETUP_IS_CLOSED), 'Should throw the closed meetup exception');
    }

    @IsTest
    private static void getAvailableMeetupIdForCode_meetupFull_throwException() {
        insert new Meetup__c(RegistrationLimit__c = 1);
        // a reason to mock -- even our test setup is an integration test that requires 
        // automation to work
        Meetup__c meetup = [SELECT RegistrationCode__c FROM Meetup__c LIMIT 1];
        insert new MeetupRegistration__c(FirstName__c = 'test', LastName__c = 'tester', Email__c = 'Test@Tester.com', Meetup__c = meetup.Id);
        String err;
        System.Test.startTest();
        try {
            MeetupRegistrationController.getAvailableMeetupIdForCode(meetup.RegistrationCode__c);
        } catch (AuraHandledException e) {
            err = e.getMessage();
        }
        System.Test.stopTest();
        Assert.isTrue(err.contains(MeetupRegistrationController.MEETUP_IS_FULL), 'Should throw the full meetup exception');
    }

    @IsTest
    private static void getAvailableMeetupIdForCode_meetupAvailable_returnMeetupId() {
        insert new Meetup__c(RegistrationLimit__c = 1);
        // a reason to mock -- even our test setup is an integration test that requires 
        // automation to work
        Meetup__c meetup = [SELECT RegistrationCode__c FROM Meetup__c LIMIT 1];
        System.Test.startTest();
        Id result = MeetupRegistrationController.getAvailableMeetupIdForCode(meetup.RegistrationCode__c);
        System.Test.stopTest();
        Assert.areEqual(meetup.Id, result, 'Should return the correct Id');
    }
}