force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Meetup information.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>Random and unique identifier for a meetup.</description>
    <externalId>true</externalId>
    <inlineHelpText>Random and unique identifier for a meetup.</inlineHelpText>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The maximum number of registrations for a meetup.</description>
    <inlineHelpText>The maximum number of registrations for a meetup.</inlineHelpText>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/MeetupSelectorTest.cls
@IsTest
private inherited sharing class MeetupSelectorTest {
    @TestSetup
    private static void makeData() {
        // likely use a data factory for any data generation
        // data factory + record mocking can be the same library
        // I personally like to create a record mocking framework that also tries
        // to hydrate schema-required values to mitigate risk of needing future refactors
        insert new List<Meetup__c> { 
            new Meetup__c(RegistrationLimit__c = 1), 
            new Meetup__c(RegistrationLimit__c = 1)
        }; 
    }

    @IsTest
    private static void getMeetupsByRegistrationCode_2existing_return1Queried() {
        Meetup__c openMeetup = [SELECT Id, RegistrationCode__c FROM Meetup__c LIMIT 1];

        MeetupSelector selector = new MeetupSelector();
        System.Test.startTest();
        List<Meetup__c> results = selector.getMeetupsByRegistrationCode(
            new Set<String> { openMeetup.RegistrationCode__c },
            false
        );
        System.Test.stopTest();
        
        Assert.areEqual(1, results.size(), 'Should return 1 of the 2 records');
        Assert.areEqual(openMeetup.Id, results[0].Id, 'Should return the correct meetup');
    }

    @IsTest
    private static void getMeetupsById_2existing_return1Queried() {
        Meetup__c openMeetup = [SELECT Id, RegistrationCode__c FROM Meetup__c LIMIT 1];

        MeetupSelector selector = new MeetupSelector();
        System.Test.startTest();
        List<Meetup__c> results = selector.getMeetupsById(
            new Set<Id> { openMeetup.Id },
            false
        );
        System.Test.stopTest();
        
        Assert.areEqual(1, results.size(), 'Should return 1 of the 2 records');
        Assert.areEqual(openMeetup.Id, results[0].Id, 'Should return the correct meetup');
    }
}