force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Meetup information.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The maximum number of registrations for a meetup.</description>
    <inlineHelpText>The maximum number of registrations for a meetup.</inlineHelpText>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <description>Individual user registration for a meetup.</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>MR-{0}</displayFormat>
        <label>Meetup Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Registrant email.</description>
    <inlineHelpText>Registrant email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Registrant First Name.</description>
    <inlineHelpText>Registrant First Name.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Registrant Last Name.</description>
    <inlineHelpText>Registrant Last Name.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>The meetup that a registration is for.</description>
    <inlineHelpText>The meetup that a registration is for.</inlineHelpText>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>Meetup_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tests/MeetupRegistrationTriggerHandlerTest.cls
@IsTest
private inherited sharing class MeetupRegistrationTriggerHandlerTest {

    @TestSetup
    private static void makeData() {
        insert new Meetup__c(RegistrationLimit__c = 2);
    }

    @IsTest
    private static void doBeforeInsert_singleRecordHappyPath_succeed() {
        Meetup__c meetup = [SELECT Id FROM Meetup__c LIMIT 1];
        System.Test.startTest();
        insert new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test@Tester.com', Meetup__c = meetup.Id);
        System.Test.stopTest();
        List<MeetupRegistration__c> result = [SELECT Id FROM MeetupRegistration__c WHERE Meetup__c = :meetup.Id];
        Assert.areEqual(1, result.size(), 'Should create the registration record');
    }

    @IsTest
    private static void doBeforeInsert_multipleRecordHappyPath_succeed() {
        Meetup__c meetup = [SELECT Id FROM Meetup__c LIMIT 1];
        System.Test.startTest();
        insert new List<MeetupRegistration__c> {
            new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test@Tester.com', Meetup__c = meetup.Id),
            new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test2@Tester.com', Meetup__c = meetup.Id)
        };
        System.Test.stopTest();
        List<MeetupRegistration__c> result = [SELECT Id FROM MeetupRegistration__c WHERE Meetup__c = :meetup.Id];
        Assert.areEqual(2, result.size(), 'Should create the registration record');
    }

    @IsTest
    private static void doBeforeInsert_singleRecordLimitExceeded_throwException() {
        Meetup__c meetup = [SELECT Id FROM Meetup__c LIMIT 1];
        insert new List<MeetupRegistration__c> {
            new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test@Tester.com', Meetup__c = meetup.Id),
            new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test2@Tester.com', Meetup__c = meetup.Id)
        };
        String err;
        System.Test.startTest();
        try {
            insert new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test3@Tester.com', Meetup__c = meetup.Id);
        } catch (Exception e) {
            err = e.getMessage();
        }
        System.Test.stopTest();
        List<MeetupRegistration__c> result = [SELECT Id FROM MeetupRegistration__c WHERE Meetup__c = :meetup.Id];
        Assert.areEqual(2, result.size(), 'Should not create the 3rd registration record');
        Assert.isTrue(err.contains(MeetupRegistrationTriggerHandler.REGISTRATION_LIMIT_EXCEEDED), 'Should throw the correct error');
    }

    @IsTest
    private static void doBeforeInsert_multipleRecordLimitExceeded_throwException() {
        Meetup__c meetup = [SELECT Id FROM Meetup__c LIMIT 1];
        String err;
        System.Test.startTest();
        try {
            insert new List<MeetupRegistration__c> {
                new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test@Tester.com', Meetup__c = meetup.Id),
                new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test2@Tester.com', Meetup__c = meetup.Id),
                new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test3@Tester.com', Meetup__c = meetup.Id)
            };
        } catch (Exception e) {
            err = e.getMessage();
        }
        System.Test.stopTest();
        List<MeetupRegistration__c> result = [SELECT Id FROM MeetupRegistration__c WHERE Meetup__c = :meetup.Id];
        Assert.areEqual(0, result.size(), 'Should not create any registration records');
        Assert.isTrue(err.contains(MeetupRegistrationTriggerHandler.REGISTRATION_LIMIT_EXCEEDED), 'Should throw the correct error');
    }

    @IsTest
    private static void doBeforeInsert_singleRecordEmailDupe_throwException() {
        Meetup__c meetup = [SELECT Id FROM Meetup__c LIMIT 1];
        insert new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test@Tester.com', Meetup__c = meetup.Id);
        String err;
        System.Test.startTest();
        try {
            insert new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test@Tester.com', Meetup__c = meetup.Id);
        } catch (Exception e) {
            err = e.getMessage();
        }
        System.Test.stopTest();
        List<MeetupRegistration__c> result = [SELECT Id FROM MeetupRegistration__c WHERE Meetup__c = :meetup.Id];
        Assert.areEqual(1, result.size(), 'Should not create the 2nd registration record');
        Assert.isTrue(err.contains(MeetupRegistrationTriggerHandler.REGISTRATION_DUPLICATE_EMAIL), 'Should throw the correct error');
    }

    @IsTest
    private static void doBeforeInsert_multipleRecordEmailDupe_throwException() {
        Meetup__c meetup = [SELECT Id FROM Meetup__c LIMIT 1];
        String err;
        System.Test.startTest();
        try {
            insert new List<MeetupRegistration__c> {
                new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test@Tester.com', Meetup__c = meetup.Id),
                new MeetupRegistration__c(FirstName__c = 'Test', LastName__c = 'Tester', Email__c = 'Test@Tester.com', Meetup__c = meetup.Id)
            };
        } catch (Exception e) {
            err = e.getMessage();
        }
        System.Test.stopTest();
        List<MeetupRegistration__c> result = [SELECT Id FROM MeetupRegistration__c WHERE Meetup__c = :meetup.Id];
        Assert.areEqual(0, result.size(), 'Should not create any registration records');
        Assert.isTrue(err.contains(MeetupRegistrationTriggerHandler.REGISTRATION_DUPLICATE_EMAIL), 'Should throw the correct error');
    }
}