force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Meetup information.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>Random and unique identifier for a meetup.</description>
    <externalId>true</externalId>
    <inlineHelpText>Random and unique identifier for a meetup.</inlineHelpText>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The maximum number of registrations for a meetup.</description>
    <inlineHelpText>The maximum number of registrations for a meetup.</inlineHelpText>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/tests/MeetupTriggerHandlerTest.cls
@IsTest
private inherited sharing class MeetupTriggerHandlerTest {
    @IsTest
    private static void doBeforeInsert_1HasCode1DoesNot_generateCodeOnSecond() {
        System.Test.startTest();
        insert new List<Meetup__c> {
            new Meetup__c(Name = '1', RegistrationLimit__c = 1, RegistrationCode__c = 'abcd1234'),
            new Meetup__c(Name = '2', RegistrationLimit__c = 1)
        };
        System.Test.stopTest();
        List<Meetup__c> results = [SELECT Name, RegistrationCode__c FROM Meetup__c];
        for (Meetup__c result : results) {
            if (result.Name == '1') {
                Assert.areEqual('abcd1234', result.RegistrationCode__c, 'Should not overwrite the registration code');
            } else {
                Assert.isTrue(String.isNotBlank(result.RegistrationCode__c), 'Should populate the registration code');
                Assert.isTrue(result.RegistrationCode__c.isAlphanumeric(), 'Should store an alpha numeric string');
            }
        }
    }
}