force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <description>Meetup information.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The maximum number of registrations for a meetup.</description>
    <inlineHelpText>The maximum number of registrations for a meetup.</inlineHelpText>
    <label>Registration Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Registrations__c.field-meta.xml
<CustomField>
    <fullName>Registrations__c</fullName>
    <description>The current number of registrations for the meetup.</description>
    <inlineHelpText>The current number of registrations for the meetup.</inlineHelpText>
    <label>Registrations</label>
    <summaryForeignKey>MeetupRegistration__c.Meetup__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Meetup Registration Status.</description>
    <inlineHelpText>Meetup Registration Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <description>Individual user registration for a meetup.</description>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>MR-{0}</displayFormat>
        <label>Meetup Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetupRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Registrant email.</description>
    <inlineHelpText>Registrant email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Registrant First Name.</description>
    <inlineHelpText>Registrant First Name.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Registrant Last Name.</description>
    <inlineHelpText>Registrant Last Name.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>The meetup that a registration is for.</description>
    <inlineHelpText>The meetup that a registration is for.</inlineHelpText>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>Meetup_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MeetupRegistrationController.cls
public with sharing class MeetupRegistrationController {
    @TestVisible
    private static final String REGISTRATION_CODE_REQUIRED = 'Registration code required to retrieve meetup details.';
    @TestVisible
    private static final String MEETUP_NOT_FOUND = 'Meetup was not found.';
    @TestVisible
    private static final String MEETUP_IS_CLOSED = 'Meetup is closed and cannot accept any more registrations.';
    @TestVisible
    private static final String MEETUP_IS_FULL = 'Meetup is full and cannot accept any more registrations.';
    @TestVisible
    private static final String CANNOT_PROVIDE_BLANK_REGISTRATION_VALUES = 'One or more registration details were blank.';

    @AuraEnabled
    public static Id getAvailableMeetupIdForCode(String registrationCode) {
        try {
            if (String.isBlank(registrationCode)) {
                throw new RegistrationException(REGISTRATION_CODE_REQUIRED);
            }
            // would normally have a factory similar to the services class so that this can be mockable
            // would maybe move this logic down to a service class too -- we want to keep entry points thin to promote reuse
            List<Meetup__c> meetups = new MeetupSelector().getMeetupsByRegistrationCode(new Set<String> { registrationCode }, true);
            if (meetups.isEmpty()) {
                throw new RegistrationException(MEETUP_NOT_FOUND);
            }
            if (meetups[0].Status__c == 'Closed') {
                throw new RegistrationException(MEETUP_IS_CLOSED);
            }
            if (meetups[0].Registrations__c >= meetups[0].RegistrationLimit__c) {
                throw new RegistrationException(MEETUP_IS_FULL);
            }
            return meetups[0].Id;
        } catch (Exception e) {
            // would generally move this to a more reusable service so we aren't repeating in every method
            Services.logger.error('MeetupRegistrationController.getMeetupIdForCode', e);
            AuraHandledException ex = new AuraHandledException(e.getMessage());
            ex.setMessage(e.getMessage());
            throw ex;
        }
    }

    @AuraEnabled
    public static void register(RegistrationArgs args) {
        try {
            args.validate();
            // would use data library for more flexible and holistic secure by default dml here rather than this, but using standard libs for interview problem
            Database.insert(
                new MeetupRegistration__c(
                    FirstName__c = args.firstName,
                    LastName__c = args.lastName,
                    Email__c = args.email,
                    Meetup__c = args.meetup
                ), 
                AccessLevel.User_mode
            ); 
        } catch (Exception e) {
            // would generally move this to a more reusable service so we aren't repeating in every method
            Services.logger.error('MeetupRegistrationController.register', e);
            AuraHandledException ex = new AuraHandledException(e.getMessage());
            ex.setMessage(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    // DTO for UI contract
    public inherited sharing class RegistrationArgs {
        @AuraEnabled
        public Id meetup { get; set; }
        @AuraEnabled
        public String firstName { get; set; }
        @AuraEnabled
        public String lastName { get; set; }
        @AuraEnabled
        public String email { get; set; }

        public void validate() {
            if (
                String.isBlank(this.firstName) 
                || String.isBlank(this.lastName) 
                || String.isBlank(this.email)
                || String.isBlank(this.meetup)
            ) {
                throw new RegistrationException(CANNOT_PROVIDE_BLANK_REGISTRATION_VALUES);
            }
        }
    }

    private inherited sharing class RegistrationException extends Exception {
    }
}